### ISSUE TITLE
Describe XO bias in detail

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/XO-bias-study#35]
Explain what we did and how the percentages work.

_Do we want to describe reverse bias?_

**Comment by NicMcPhee** [comment]
We want to mention reverse bias, say it didn't do anything, and not say anything further.

**Comment by MKDramdahl** [comment]
Not going to mark this as complete quite yet; because the text in the Crossover Bias section is still very clunky, awkward, and repetitive; but I believe at this point that the section does include all the necessary information on what crossover bias is and does and why we are using it, along with information on the various levels of bias implemented. Let me know if I missed anything.

**Comment by NicMcPhee** [comment]
I think this is pretty reasonable shape (certainly enough to be called a complete first draft), so I'm going to mark it as closed. I'm sure we'll continue to make changes, but I don't think we need this specific issue to keep hanging around.
